# A NYU Capstone Project
# The Guild Manager by JV · CC · ZQ · ZF


# This is a workflow to test and deploy The Guild Manager.
name: Master_CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1

    - name: Build
      run: CI=false npm run build